[general]
# Path to the project folder
project_path = /Users/mabecker/Documents/Code/ES-Lab-Kit/Software/Projects
# Target platform. Default, if not specified, is rp2350
target = rp2350
# SWD frequency
frequency = 4_000_000
# Duration of the trace collection in seconds. The target is halted afterwards
measure_seconds = 2
# ISR ID for the FreeRTOS tick ISR on each core
tickId = 15,42

[Pico2_FreeRTOS_SRAM]
# Address of the trace buffers on the target
buffer0 = 0x2008001c
buffer1 = 0x2008100c
# Length of the trace buffers (each), in byte
bufferSize = 2000

[Pico2_FreeRTOS_PSRAM]
# Address of the trace buffers on the target
buffer0 = 0x15000000
buffer1 = 0x15004E20
# Length of the trace buffers (each), in byte
bufferSize = 20000

[RPI_Linux]
# !!!Linux tracing is experimental!!!
# user@targetAddress
target = mabecker@130.229.133.56
# Full path to the application to be traced
target_path = /home/mabecker/Code/bpfTrace/MultiThreadExample/build/multiThreadExample
# Base path where the recorder files are located
recorderBase_path = /home/mabecker/Code/bpfTrace/
# Name of the trace application on the target
recorder_filename = traceApp.py
# Name of the generated trace file
trace_filename = trace.txt
# Consider user-events when parsing the task execution
user_events = True