[general]
# Path where the application can find ps2pdf utility
ps2pdf_path = /usr/local/bin

[Pico2_FreeRTOS]
# Path where the application can find openocd
openocd_path = /Users/mabecker/.pico-sdk/openocd/0.12.0+dev
# Address of the trace buffers on the target
buffer0 = 0x2008001c
buffer1 = 0x2008100c
# Length of the trace buffers (each), in byte
bufferSize = 2000
# ISR ID for the scheduling tick on each core
tickId = 15,42

[Pico2_FreeRTOS_PSRAM]
# Path where the application can find openocd
openocd_path = /Users/mabecker/.pico-sdk/openocd/0.12.0+dev
# Address of the trace buffers on the target
buffer0 = 0x15000000
buffer1 = 0x15004E20
# Length of the trace buffers (each), in byte
bufferSize = 20000
#2000000
# ISR ID for the scheduling tick on each core
tickId = 15,42

#[STM_FreeRTOS]
# Path where the application can find openocd
#openocd_path = /usr/local/bin
# Address of the trace buffers on the target
#buffer0 = 0x10000000
# Length of the trace buffers (each), in byte
#bufferSize = 4000
# ISR ID for the scheduling tick
#tickId = 15

[RPI_Linux]
# user@targetAddress
#target = mabecker@ras-mabecker.ees.kth.se
target = mabecker@130.229.133.56
# Full path to the application to be traced
target_path = /home/mabecker/Code/bpfTrace/MultiThreadExample/build/multiThreadExample
# Base path where the recorder files are located
recorderBase_path = /home/mabecker/Code/bpfTrace/
# Name of the trace application on the target
recorder_filename = traceApp.py
# Name of the generated trace file
trace_filename = trace.txt
# Consider user-events when parsing the task execution
user_events = True